profiles:
  - type: local
    name: ssh2sftp_win_template
    icon: fas fa-terminal
    options:
      command: c:\Git\usr\bin\sftp.exe
      env: {}
      cwd: ''
      args:
        - '-oStrictHostKeyChecking=no'
        - '-oServerAliveInterval=30'
        - '-oServerAliveCountMax=1051200'
        - '-oTCPKeepAlive=yes'
    group: ssh2sftp_template
    id: local:custom:ssh2sftp_win_template:c617da05-d05c-482d-8ca6-3c7eb99452e9
    disableDynamicTitle: true
    isTemplate: true
  - type: local
    name: ssh2sftp_linux_template
    icon: fas fa-terminal
    options:
      command: /usr/bin/sftp
      env: {}
      cwd: ''
      args:
        - '-oStrictHostKeyChecking=no'
        - '-oServerAliveInterval=30'
        - '-oServerAliveCountMax=1051200'
        - '-oTCPKeepAlive=yes'
    group: ssh2sftp_template
    id: local:custom:ssh2sftp_linux_template:6c4bcc75-f690-482a-a882-40e1c9851a3d
    disableDynamicTitle: true
    isTemplate: true
  - type: local
    name: ssh2sftp_mac_template
    icon: fas fa-terminal
    options:
      command: /usr/local/opt/openssh/bin/sftp
      args:
        - '-oStrictHostKeyChecking=no'
        - '-oServerAliveInterval=30'
        - '-oServerAliveCountMax=1051200'
        - '-oTCPKeepAlive=yes'
      env: {}
      cwd: ''
    id: local:custom:ssh2sftp_mac_template:33162a26-7807-4c5e-ac2d-68cd2d9a4a24
    group: ssh2sftp_template
    disableDynamicTitle: true
    isTemplate: true